


import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "../components/navbar/Navbar";
import Footer from "./footer";
export const sofiaPro = localFont({
  src: [
    {
      path: "../../public/sofia-pro/regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/sofia-pro/medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/sofia-pro/bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-sofia-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${sofiaPro.variable} antialiased font-sans font-normal`}>
        <Navbar />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
